export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const UPDATE_CURRENT_STEP = 'UPDATE_CURRENT_STEP';
export const STATR_EVISA_REQUEST = 'STATR_EVISA_REQUEST';
export const EVISA_REQUEST = 'EVISA_REQUEST';
export const EVISA_REQUEST_SUCCESS = 'EVISA_REQUEST_SUCCESS';
export const EVISA_REQUEST_FAILED = 'EVISA_REQUEST_FAILED';
export const UPDATE_BALANCE_REQUEST = 'UPDATE_BALANCE_REQUEST';
export const FINISHED_REDIRECT = 'FINISHED_REDIRECT';

export const START_INIT_NATIONALITY = 'INIT_NATIONALITY';
export const INIT_NATIONALITY = 'INIT_NATIONALITY';
export const INIT_NATIONALITY_SUCCESS  = 'INIT_NATIONALITY_SUCCESS';
export const INIT_NATIONALITY_FAILED  = 'INIT_NATIONALITY_FAILED';

export const START_GETTING_EVISA_TYPES = 'START_GETTING_EVISA_TYPE';
export const GETTING_EVISA_TYPES = 'GETTING_EVISA_TYPE';
export const GETTING_EVISA_TYPES_SUCCESS = 'GETTING_EVISA_TYPES_SUCCESS';
export const GETTING_EVISA_TYPES_FAILED = 'GETTING_EVISA_TYPES_FAILED';

export const START_GETTING_EVISA_SETTINGS = 'START_GETTING_EVISA_SETTINGS';
export const GETTING_EVISA_SETTINGS = 'GETTING_EVISA_SETTINGS';
export const GETTING_EVISA_SETTINGS_SUCCESS = 'GETTING_EVISA_SETTINGS_SUCCESS';
export const GETTING_EVISA_SETTINGS_FAILED = 'GETTING_EVISA_SETTINGS_FAILED';
export const HANDLE_EVISA_SETTINGS_MODAL = 'HANDLE_EVISA_SETTINGS_MODAL';

export const START_TRAVELLER_VALIDATOR  = 'START_TRAVELLER_VALIDATOR';
export const TRAVELLER_VALIDATOR = 'TRAVELLER_VALIDATOR';
export const TRAVELLER_VALIDATOR_SUCCESS = 'TRAVELLER_VALIDATOR_SUCCESS';
export const TRAVELLER_VALIDATOR_FAILED = 'TRAVELLER_VALIDATOR_FAILED';
export const HANDLE_TRAELLER_FORM_MODAL = 'HANDLE_TRAELLER_FORM_MODAL';
export const HANDLE_DELETE_TRAVELLER = 'HANDLE_DELETE_TRAVELLER';

export const START_EVISA_VALIDATOR  = 'START_EVISA_VALIDATOR';
export const EVISA_VALIDATOR = 'EVISA_VALIDATOR';
export const EVISA_VALIDATOR_SUCCESS = 'EVISA_VALIDATOR_SUCCESS';
export const EVISA_VALIDATOR_FAILED = 'EVISA_VALIDATOR_FAILED';

export const START_GETTING_EVISA_REQUESTS = 'START_GETTING_EVISA_REQUESTS';
export const GETTING_EVISA_REQUESTS = 'GETTING_EVISA_REQUESTS';
export const GETTING_EVISA_REQUESTS_SUCCESS = 'GETTING_EVISA_REQUESTS_SUCCESS';
export const GETTING_EVISA_REQUESTS_FAILED = 'GETTING_EVISA_REQUESTS_FAILED';

export const START_INIT_DESTINATIONS = 'START_INIT_DESTINATIONS';
export const INIT_DESTINATIONS = 'INIT_DESTINATIONS';
export const INIT_DESTINATIONS_SUCCESS  = 'INIT_DESTINATIONS_SUCCESS';
export const INIT_DESTINATIONS_FAILED  = 'INIT_DESTINATIONS_FAILED';

export const START_INIT_AGENCIES = 'START_INIT_AGENCIES';
export const INIT_AGENCIES = 'INIT_AGENCIES';
export const INIT_AGENCIES_SUCCESS  = 'INIT_AGENCIES_SUCCESS';
export const INIT_AGENCIES_FAILED  = 'INIT_AGENCIES_FAILED';

export const START_EVISA_DETAILS_REQUEST = 'START_EVISA_REQUEST';
export const EVISA_DETAILS = 'EVISA_DETAILS';
export const EVISA_DETAILS_SUCCESS = 'EVISA_DETAILS_SUCCESS';
export const EVISA_DETAILS_FAILED = 'EVISA_DETAILS_FAILED';

export const START_EVISA_ACTION_REQUEST = 'START_EVISA_ACTION_REQUEST';
export const EVISA_ACTION = 'EVISA_ACTION';
export const EVISA_ACTION_SUCCESS = 'EVISA_ACTION_SUCCESS';
export const EVISA_ACTION_FAILED = 'EVISA_ACTION_FAILED';
export const EVISA_ACTION_RESET_MODAL = 'EVISA_ACTION_RESET_MODAL';